### ISSUE TITLE
Possibility to add class to captcha wrapper + choose where to append it instead of bottom of form

### ISSUE THREAD

**Issue by thaoms** [hungluu/honeyjs#26]
I rather have the captcha above my submit button instead of below it.
Adding a class to the wrapper would make it easier to align the element.

**Comment by hungluu** [comment]
Sorry for my late responding. I have a while off the line but now I'm back.

There is a placeholder option, you can put a div with class `"honeyjs"` for your custom position of captcha so you can put the captcha anywhere you want ( even on top of the form :D ). 

Here is some lines of example code
```
<form method="POST" id="secured">
  <input type="email" name="email">
  <input type="password" name="password">
  <input type="hidden" name="crsf-token" value="adas35297fffksjzzFE">
  <!-- an optional placeholder for honeyjs to load components -->
  <div class="honeyjs"></div >
  <button type="submit"> Submit </button>
</form>
```

The captcha box will be loaded into where the `<div class="honeyjs></div >` is placed

**Comment by hungluu** [comment]
If you have any other problems, please let me know.
