### ISSUE TITLE
Not really an issue but please let me post this anyway

### ISSUE THREAD

**Issue by OSD-Kyler** [hungluu/honeyjs#27]
I was using this library and then my colleagues came and we decided to apply it to our project. He said this library really changed his life and it touched my heart.
My company's people are so grateful. Am proud to say cool library wow thanks for sharing. Kudos to the author 😘 😘 😘

**Comment by osd-henry** [comment]
Cool. Thanks buddy. Please let me know if I need any improvements into this or my other libraries 🍻

**Comment by hungluu** [comment]
Cool. Thanks buddy. Please let me know if I need any improvements into this or my other libraries 🍻
